services:
    laravel:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: presensi
        ports:
            - 8001:80
        env_file:
            - ./.env
        volumes:
            - local_data:/app/storage/app/public
        networks:
            - shared-net
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/"]
            interval: 5000s
            timeout: 10s
            retries: 3

networks:
  shared-net:
    external: true

volumes:
  local_data:


